# These directories will be used by the code
directories:
  # 1. Pickle to Dictionary settings
  # This file will be read from the 'music_pattern_directory' directory
  # but it can contain glob patterns eg ? or *, and then all matching files will be read and concatenated
  pickle_pattern_information        : inputs/mtc_ann/data/5gram_kg_data.pkl
  #metadata csv file, this file will be used to retrieve the metadata of tunes
  metadata_csv_file: inputs/mtc_ann/metadata/mtc_metadata_revised.csv

  # JAMS files will be created for each tune and they will be saved in 'JAMS_files_directory'
  # NOTE: here we need absolute path - this is requirement for SPARQL query
  JAMS_files_dir         : D:/vc/patterns-knowledge-graph/P2KG-Pipeline/JAMS/mtc_ann/5gram/
  # 2. Dictionary to JAMS - Settings
  # schema directory
  schemas_directory : ./schemas
  # schema file
  schema_file :  pattern_fonn.json

jams_annotations:
  # 1. Pickle to Dictionary settings
  # no setting required
  # 2. pickle to jams
  corpus_name : mtc_ann
  annotator_name : Peter van Kranenburg
  data_source : program
  corpus : MTC-ANN
  version : 2
  email : peter.van.kranenburg@meertens.knaw.nl
  annotation_tools : FONN-Tool
  schema_name : pattern_fonn
  pattern_type : feature='diatonic scale degree', level='accent', n_vals=5
  tune_base_url : https://www.liederenbank.nl/mtc/