# How many distinct pieces with pattern annotations are there in this KG?

PREFIX jams: <http://w3id.org/polifonia/ontology/jams/>

SELECT (COUNT(?piece) AS ?count)
WHERE {
  ?s jams:isJAMSAnnotationOf ?piece.
} 