# Given a tune, find related tunes by common patterns and ensure in a different corpus


PREFIX jams: <http://w3id.org/polifonia/ontology/jams/>
PREFIX mm:   <http://w3id.org/polifonia/ontology/music-meta/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?givenTunetitle ?matchedTuneTitle ?SharedPattern ?PatternComplexity
WHERE { 
VALUES ?givenTune {'Drowsy Maggie'}
?tune mm:title ?givenTune .
?tuneFile jams:isJAMSAnnotationOf ?tune .
?tuneFile jams:includesObservation ?observation .
?observation jams:ofPattern ?SharedPattern .
?observation jams:hasPatternComplexity ?PatternComplexity .
?anotherTuneFile jams:includesObservation ?anotherTuneObser .
?anotherTuneFile jams:isJAMSAnnotationOf ?anotherTune .
?anotherTuneObser  jams:ofPattern ?SharedPattern .
FILTER(?tuneFile != ?anotherTuneFile) .
?tune mm:title ?givenTunetitle .
?tune jams:tuneId ?givenTuneId .  
?anotherTune mm:title ?matchedTuneTitle . 
?anotherTune jams:tuneId ?matchedTuneId .  
}

TODO: filter that the found tunes are in a different corpus.


    ?composition rdfs:label ?givenTuneTitle.
    ?ann jams:isJAMSAnnotationOf ?composition.    
    ?jfile prov:wasDerivedFrom ?corpus_name.
    ?jfile prov:wasMemberOf ?uri.