# Given a tune, find related tunes by common patterns and ensure in a different corpus

PREFIX jams: <http://w3id.org/polifonia/ontology/jams/>
PREFIX mm:   <http://w3id.org/polifonia/ontology/music-meta/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT ?anotherTune ?matchedTuneTitle
WHERE { 
  ?tuneAnn jams:isJAMSAnnotationOf <http://w3id.org/polifonia/resource/tunes/thesession20211212/MusicEntity/3822> .
  ?tuneAnn jams:includesObservation ?observation .
  ?observation jams:ofPattern ?SharedPattern .
  ?anotherTuneAnn jams:includesObservation ?anotherTuneObservation .
  ?anotherTuneAnn jams:isJAMSAnnotationOf ?anotherTune .
  ?anotherTuneObservation jams:ofPattern ?SharedPattern .
  FILTER(?tuneAnn != ?anotherTuneAnn) .
  # ?anotherTune mm:title ?matchedTuneTitle .
  #?anotherTune jams:tuneId ?matchedTuneId .
}

# TODO: filter that the found tunes are in a different corpus.

# <http://w3id.org/polifonia/resource/MusicalComposition/12913e6ca5c9fdddb6884c46fd6513189b57c18f> prov:wasDerivedFrom ?jfile.  
# ?jfile prov:wasDerivedFrom ?corpus_label.  

#    ?composition rdfs:label ?givenTuneTitle.
#    ?ann jams:isJAMSAnnotationOf ?composition.    
#    ?jfile prov:wasDerivedFrom ?corpus_name.
#    ?jfile prov:wasMemberOf ?uri.