# Given an n-gram pattern, find tunes where it is found

PREFIX jams: <http://w3id.org/polifonia/ontology/jams/>
PREFIX mm:   <http://w3id.org/polifonia/ontology/music-meta/>
PREFIX xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX core: <http://w3id.org/polifonia/ontology/core/>

SELECT distinct ?pattern ?tuneId ?tuneTitle ?TuneType ?TuneSignature
WHERE { 
    VALUES ?contents {"3, 3, 5, 1"}
    ?pattern xyz:pattern_content ?contents .
    ?observation  jams:ofPattern ?pattern .
    ?tuneFile jams:includesObservation ?observation .
    ?tuneFile jams:isJAMSAnnotationOf ?tune .
    ?tune core:title ?tuneTitle .
    ?tune mm:FormType ?TuneType .
    ?tune jams:timeSignature ?TuneSignature .
}