# Given a tune title, find its corpus name and URI

PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?corpus_label
WHERE
{ 
   <http://w3id.org/polifonia/resource/MusicalComposition/12913e6ca5c9fdddb6884c46fd6513189b57c18f> prov:wasDerivedFrom ?jfile.  
   ?jfile prov:wasDerivedFrom ?corpus_label.  
} 
