# Given a tune title, find its corpus name and URI

PREFIX jams: <http://w3id.org/polifonia/ontology/jams/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix mm:   <http://w3id.org/polifonia/ontology/music-meta/>
prefix prov: <http://www.w3.org/ns/prov#>

SELECT ?corpus_label
WHERE
{ 
   <http://w3id.org/polifonia/resource/MusicalComposition/12913e6ca5c9fdddb6884c46fd6513189b57c18f> prov:wasDerivedFrom ?jfile.  

   ?jfile prov:wasMemberOf ?corpus_uri.
   ?jfile prov:wasDerivedFrom ?corpus_label.  
} 
