# Given a tune, find members of the same tune family (as annotated)

PREFIX jams: <http://w3id.org/polifonia/ontology/jams/>

SELECT distinct ?label
WHERE { 
  VALUES ?givenTune {<http://w3id.org/polifonia/resource/MusicalComposition/12913e6ca5c9fdddb6884c46fd6513189b57c18f>} 
  ?givenTune jams:tuneFamily ?tuneFamily.
  ?matchedTune jams:tuneFamily ?tuneFamily;
               rdfs:label ?label.
}