# Find all pattern types in the KG and the number of each

PREFIX jams: <http://w3id.org/polifonia/ontology/jams/>

SELECT ?patternType (COUNT(?patternType) AS ?occurrences) 
WHERE { 
    ?pattern jams:hasPatternType ?patternType.
} 
GROUP BY ?patternType 
ORDER BY DESC(?occurrences) 
LIMIT 10 