# find all the different types of tunes (reel, jig, etc)

prefix mm:   <http://w3id.org/polifonia/ontology/music-meta/>

SELECT DISTINCT ?form 
WHERE 
{
?tune mm:hasFormType ?formURI.
?formURI mm:tuneTypeName ?form.
}