# Find all tune titles (which have annotations) in this KG 

PREFIX jams: <http://w3id.org/polifonia/ontology/jams/>
PREFIX core: <http://w3id.org/polifonia/ontology/core/>

SELECT ?title
WHERE {
  ?s jams:isJAMSAnnotationOf ?piece.
  ?piece core:title ?title.
} 